# Generated by Django 2.2 on 2021-03-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='Blog',
        ),
    ]
