# Generated by Django 2.2 on 2021-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
    ]
